### ISSUE TITLE
積み残し

### ISSUE THREAD

**Issue by sasano8** [sasano8/sample_dbt#1]
- [ ] : 取り込んだCSVにプライマリキーをつけたい
- [ ] : 単なるビューやマテリアライズドビューの戦略を身につけたい
- [ ] : opnelineage との連携
- [ ] : カスタムローダー：難しそう

**Comment by sasano8** [comment]
プライマリーキーをつけるには

schema.yml

```
# schema.ymlファイル
version: 2

seeds:
  - name: your_seed_table  # 例: your_seed_table
    columns:
      - name: id           # プライマリーキーにしたい列名
        tests:
          - unique
          - not_null
```
